# _starcup pre-commit.com config
# You don't have to install it yourself, CI applies fixes to PRs automatically.

# don't touch upstream files
files: "_starcup/"
repos:
- repo: "https://github.com/pre-commit/pre-commit-hooks"
  rev: "cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b"  # v5.0.0
  hooks:
  # File checkers
  - id: check-yaml
    # only check prototypes, maps would be too slow
    files: "^Resources/Prototypes/_starcup/.*\\.yml"
    # !type:... doesn't work without somehow loading SS14, which would probably make commits take years
    args: [ "--unsafe" ]
  - id: check-json
    # only need to check meta.json files
    files: "^Resources/Textures/_starcup/.*meta\\.json$"
  - id: check-xml
    # Check all ui XAML files
    # Can't check guidebook "xml" as it is a monster
    files: "^Content.Client/_starcup/.*\\.xaml$"
    types: ["text"]
  - id: check-toml
    files: "^Resources/ConfigPresets/.*\\.toml$"
  - id: check-merge-conflict
  # Fixers that can and will change commits to PRs
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: fix-byte-order-marker
  - id: pretty-format-json
    # Format texture meta.json files
    files: "^Resources/Textures/_starcup/.*meta\\.json$"
    args: [ "--autofix", "--indent", "4", "--no-ensure-ascii", "--no-sort-keys" ]
