- type: gameMap
  id: Train
  mapName: 'Train'
  mapPath: /Maps/_starcup/train.yml
  maxRandomOffset: 0
  randomRotation: false
  minPlayers: 35
  maxPlayers: 70
  stations:
    Train:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: 'Train "Sentipode" {0}-{1}'
          nameGenerator:
            !type:SyndicateNameGenerator
            prefixCreator: 'ED'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/_starcup/Shuttles/SYND_EvacShip.yml # starcup: added SYND_EvacShip.yml
        - type: StationJobs
          availableJobs: # 53 jobs total w/o latejoins & interns, 65 jobs total w/ latejoins & interns
            #command (8)
            Captain: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            HeadOfSecurity: [ 1, 1 ]
            ChiefMedicalOfficer: [ 1, 1 ]
            ChiefEngineer: [ 1, 1 ]
            ResearchDirector: [ 1, 1 ]
            Quartermaster: [ 1, 1 ]
            AdministrativeAssistant: [ 1, 1 ]
            #service (11 - 12)
            Bartender: [ 1, 1 ]
            Botanist: [ 2, 2 ]
            Chef: [ 1, 1 ]
            Janitor: [ 2, 2 ]
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ 2, 3 ]
            Reporter: [ 1, 1 ]
            #engineering (6)
            AtmosphericTechnician: [ 2, 2 ]
            StationEngineer: [ 4, 4 ]
            TechnicalAssistant: [ 3, 3 ] #intern, not counted
            #medical (5)
            Chemist: [ 2, 2 ]
            MedicalDoctor: [ 2, 2 ]
            MedicalIntern: [ 2, 2 ] #intern, not counted
            Paramedic: [ 1, 1 ]
            #science (6)
            Scientist: [ 4, 4 ]
            Roboticist: [ 1, 2 ]
            ResearchAssistant: [ 2, 2 ] #intern, not counted
            #security (9 - 10)
            Warden: [ 1, 1 ]
            SecurityOfficer: [ 6, 6 ]
            SecurityCadet: [ 3, 3 ] #intern, not counted
            Lawyer: [ 1, 2 ]
            Detective: [ 1, 1 ]
            #supply (6)
            SalvageSpecialist: [ 3, 3 ]
            Courier: [ 2, 3 ]
            CargoTechnician: [ 3, 3 ]
            CargoAssistant: [ 2, 2 ] #intern, not counted
            #civilian (3+)
            Passenger: [ -1, -1 ] #infinite, not counted
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
            #silicon (2)
            Borg: [ 2, 2 ]
