# begin starcup
- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Empty
#  - Amber
#  - Bagel
#  - Box
#  - Elkridge
#  - Fland
#  - Marathon
#  - Oasis
#  - Packed
#  - Plasma
#  - Reach
#  - Exo
# end starcup
