# Rubber ammo, removed from upstream

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolRubber
  result: MagazinePistolRubber
  materials:
    Steel: 25
    Plastic: 120

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumRubber
  result: SpeedLoaderMagnumRubber
  materials:
    Steel: 50
    Plastic: 150

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxPistolRubber
  result: MagazineBoxPistolRubber
  materials:
    Plastic: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxMagnumRubber
  result: MagazineBoxMagnumRubber
  materials:
    Plastic: 240
