- type: job
  id: AdministrativeAssistant
  name: job-name-admin-assistant
  description: job-description-admin-assistant
  playTimeTracker: JobAdminAssistant
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # starcup: 25 hours to 5 hours
  startingGear: AdminAssistantGear
  icon: "JobIconAdminAssitant"
  supervisors: job-supervisors-command
  canBeAntag: false
  access:
  - Command
  - Maintenance
  # begin starcup
  - Bar
  - Cargo
  - Cryogenics
  - Engineering
  - External
  - Kitchen
  - Medical
  - Research
  - Service
  # end starcup
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff

- type: startingGear
  id: AdminAssistantGear
  equipment:
    #eyes: ClothingEyesHudCommand # starcup: moved to loadouts
    belt: ClothingBeltPaperworkFilled
    id: AdminAssistantPDA
    pocket1: RubberStampAdminAssistant
    pocket2: AccessConfigurator # To assist with secure closets access configurations / airlock configs should a head need it.
    ears: ClothingHeadsetCommandSyndie # starcup
  storage:
    back:
    - Flash

# begin starcup: add chameleon outfit
- type: chameleonOutfit
  id: AdminAssistantChameleonOutfit
  job:  AdministrativeAssistant
  equipment:
    Head: ClothingHeadHatCommandSoftSyndie
    Eyes: ClothingEyesHudCommandSyndie
    Mask: ClothingMaskBreath
    Neck: ClothingNeckScarfStripedPurple
    OuterClothing: ClothingOuterVest
    Gloves: ClothingHandsGlovesHop
# end starcup
