- type: latheRecipePack
  id: SecurityRubberAmmoStatic
  recipes:
  - MagazinePistolRubber
  - SpeedLoaderMagnumRubber
#  - SpeedLoaderSpecialRubber # starcup: we don't have this yet
#  - MagazineRifleRubber # starcup: we don't have this yet
#  - MagazineLightRifleRubber # starcup: we don't have this yet
  - MagazineBoxPistolRubber
  - MagazineBoxMagnumRubber
#  - MagazineBoxLightRifleRubber # starcup: we don't have this yet
#  - MagazineBoxRifleRubber # starcup: we don't have this yet
#  - MagazineBoxSpecialRubber # starcup: we don't have this yet
