name: "Close Stale Issues & PRs"

on:
  workflow_dispatch:
  schedule:
   - cron: '0 10 * * *'

jobs:
  close-stale:
    runs-on: ubuntu-latest
    steps:
      - name: "Close Stale Issues & PRs"
        uses: actions/stale@v9.1.0
        with:
          days-before-stale: 14
          days-before-close: 14
          stale-issue-message: 'This issue has been marked as stale because it has been inactive for more than 14 days. It will be closed in another 14 days if there is no activity.'
          close-issue-message: 'We close issues that have been inactive for four weeks in an attempt to keep our backlog from piling up. Please re-open this issue if you are still experiencing a problem or have new information to contribute.'
          stale-pr-message: 'This pull request has been marked as stale because it has been inactive for more than 14 days. Please update this pull request or it will be automatically closed in 14 days.'
          close-pr-message: 'We close pull requests that have been inactive for four weeks in an attempt to keep our backlog from piling up. Please update this pull request or request a review to bring this back up with our team.'
          stale-pr-label: stale
